version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - /home/obohov/Documents/docker-compose/nginx-php/nginx/www:/usr/share/nginx/html
      - /home/obohov/Documents/docker-compose/nginx-php/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - nginxphp
  php:
    image: php:7.2-fpm
    volumes:
      - /home/obohov/Documents/docker-compose/nginx-php/nginx/www:/usr/share/nginx/html
    networks:
      - nginxphp

networks:
    nginxphp:

